### PR TITLE
Баташев - Лабораторная работа #1

### PR DESCRIPTION
**Pull request by alexbatashev**
The following unit tests has been added:
- Add three numbers
- Operations priority is correct
- Multiply by zero
- Imaginary unit square
- Imaginary unit cube

### CODE REVIEW

**Comment by alexbatashev** [comment]
@TheSanchouz please code review

**Comment by TheSanchouz** [comment]
:+1:

**Comment by alexbatashev** [comment]
@kirill-korniakov code review please

**Comment by alexbatashev** [comment]
@p-dd code review please

**Comment by p-dd** [comment]
👍

**Comment by TheG1uy** [comment]
@alexbatashev 
Все ок.

**Pull request merged**
