### PR TITLE
Мишин И.А. 381803-2 ЛР1

### PR DESCRIPTION
**Pull request by Iliamish**
### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

### CODE REVIEW

**Comment by dkurt** [comment]
Please request a review from some of the students.

**Comment by Iliamish** [comment]
@MADZEROPIE @andrewkin77 @BrandonRTL  please review my code

**Review by MADZEROPIE — APPROVED** [review]
_**My job here is done**_

**Comment by dkurt** [comment]
@MADZEROPIE, I must disagree with your review. Tests are weak because they check for defaul zero values. They will pass even in case of the following implementation:
```
ComplexNumber ComplexNumber::operator+(const ComplexNumber& z) const {
    ComplexNumber sum;
    return sum;
}
```

**Comment by Iliamish** [comment]
> @MADZEROPIE, I must disagree with your review. Tests are weak because they check for defaul zero values. They will pass even in case of the following implementation:
> 
> ```c++
> ComplexNumber ComplexNumber::operator+(const ComplexNumber& z) const {
>     ComplexNumber sum;
>     return sum;
> }
> ```

I think that the tests that cover this case have already been implemented by other participants. And the task was to come up with a test that was not implemented

**Comment by dkurt** [comment]
@Iliamish, Please just check with non-default result. Otherwise test is not reliable (I've shown at least one example when it can miss the problem).

**Review by andrewkin77 — APPROVED** [review]
Looks good to me

**Pull request merged**
