### PR TITLE
Assemien Benie B.O. 381806-4. ЛР1 (#155)

### PR DESCRIPTION
**Pull request by bruceeewayne**
[test_BRICE_ASSEMIEN_complex_number.zip](https://github.com/UNN-ITMM-Software/devtools-course-practice/files/6246712/test_BRICE_ASSEMIEN_complex_number.zip)
Assemien Benie B.O. 381806-4. ЛР1 (#150)

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [x] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [x] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

### CODE REVIEW

**Comment by WerWebWer** [comment]
Неправильно составлен PR

**Comment by dkurt** [comment]
Изменения должны добавляться с помощью `git add`

**Comment by dkurt** [comment]
king reminder. Please use `git add` to include modified files and then `git commit ...`

**Comment by dkurt** [comment]
see https://github.com/UNN-ITMM-Software/devtools-course-practice/pull/156

**Pull request closed without merging**
