### PR TITLE
Митягина - Лабораторная работа №1

### PR DESCRIPTION
**Pull request by 381706-1Mityagina**

### CODE REVIEW

**Comment by 381706-1Mityagina** [comment]
@381706-1VlasovAndrey
could you take a look?

**Comment by 381706-1VlasovAndrey** [comment]
👍

**Comment by 381706-1Mityagina** [comment]
@381706-1GolubevaAnna
could you take a look?

**Comment by 381706-1GolubevaAnna** [comment]
:+1:

**Comment by 381706-1Mityagina** [comment]
@kirill-korniakov

**Pull request merged**
