### PR TITLE
Круглов - Лабораторная работа #1

### PR DESCRIPTION
**Pull request by akruglov18**

### CODE REVIEW

**Comment by akruglov18** [comment]
@KimNikita, @BakinaKA

**Review by KimNikita — COMMENTED** [review]
It's better to use EXPECT_DOUBLE_EQ instead EXPECT_EQ

**Comment by akruglov18** [comment]
@KimNikita, @BakinaKA

**Review by BakinaKA — APPROVED** [review]
LGTM

**Review by KimNikita — APPROVED** [review]

**Comment by akruglov18** [comment]
@dkurt

**Pull request merged**
