### PR TITLE
Galindo Javier laboratory 1

### PR DESCRIPTION
**Pull request by JavierGalindoToledo**

### CODE REVIEW

**Comment by JavierGalindoToledo** [comment]
@booka24
@bloodreina5
Please review

**Comment by bloodreina5** [comment]
good work

**Review by bloodreina5 — APPROVED** [review]

**Comment by booka24** [comment]
Excellent

**Review by booka24 — APPROVED** [review]

**Comment by JavierGalindoToledo** [comment]
@SHVlader

**Pull request merged**
