### PR TITLE
Иванов - Лабораторная работа #1

### PR DESCRIPTION
**Pull request by IvanovAA-bin**

### CODE REVIEW

**Comment by KimNikita** [comment]
It's better to use EXPECT_DOUBLE_EQ instead EXPECT_EQ

**Comment by IvanovAA-bin** [comment]
@KimNikita
@VanyushkovMM

**Comment by VanyushkovMM** [comment]
After the changes (expect_eq -> expect_double_eq) everything is fine

**Review by KimNikita — APPROVED** [review]

**Review by VanyushkovMM — APPROVED** [review]

**Comment by IvanovAA-bin** [comment]
@SHVlader

**Pull request merged**
