### PR TITLE
Чистов В.М. 381806-2. ЛР1

### PR DESCRIPTION
**Pull request by mark0wka**
### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

### CODE REVIEW

**Comment by mark0wka** [comment]
@LaQerty @Alex-Andr-19  @OnlyDeniko

**Review by Alex-Andr-19 — COMMENTED** [review]
В третьем тесте одно вычисление разнесено на 2 строчки.

**Review by LaQerty — COMMENTED** [review]
`INSTANTIATE_TEST_CASE_P(/**/, Chistov_Vladimir_ComplexNumberTest_Param,
    testing::Combine(
        testing::Values(2.3, 1.1),
        testing::Values(7.8, 15.3),
        testing::Values(3.7, 9.2),
        testing::Values(6.6, 8.4)
    )
);`
Увеличь диапазон значений.

**Review by Alex-Andr-19 — APPROVED** [review]

**Review by LaQerty — APPROVED** [review]

**Review by OnlyDeniko — APPROVED** [review]
LGTM

**Pull request merged**
